config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    resources :comments
  end
  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'static_pages#index'

  get 'static_pages/landing_page'
  
  get 'static_pages/about'
  
  get 'static_pages/contact'

  post 'static_pages/thank_you'

  post 'payments/create'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout' } , :controllers => { :registrations => "user_registrations" } 

  # actioncable
  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  has_many :orders
  has_many :comments

  def highest_rating_comment
    comments.rating_desc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource
  
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if(Rails.env.development?)
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        # use ilike for case insensitivity on postres
        @products = Product.where("name ilike ?", "%#{search_term}%")
      end
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], per_page: 3)
  end


  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
  end

app/helpers/products_helper.rb
module ProductsHelper
	 def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
         <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :colour %>
      <%= f.text_field :colour, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="reviews-ratings">
  <% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
  <p>
    <%= f.label :body, "Comments" %><br>
    <%= f.text_area :body %>
  </p>
</div>
<div class="rating">
  <h4>Rate me!</h4>
</div> 
  <p>
  <%= f.submit "Submit" %>
  </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class= "product-table">
  <div class="col-xs-12 col-sm-6 col-md-4">
    <%= image_tag(product.image_url, class: "img-responsive") if product.image_url %>
    <% cache product do %>
    <h2><%= product.name %></h2>
    <p><strong>Colour:   </strong><%= product.colour %></p>
    <p><strong>Price:   </strong><%= number_to_currency(product.price) %></p>
    <p><strong>Description:   </strong><%= product.description %></p>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </div>
</div> 

app/views/products/edit.html.erb
  <h1>Editing Product</h1>
 
 <div class="edit-page"
  <div class="form">
    <%= render 'form', product: @product %>
    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class= "product-table">
<h1>Products</h1>
  <% cache(cache_key_for_products) do %>
    <%= render @products %>
  <% end %>
</div>

<% if signed_in? && current_user.admin? %>
 <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<div class="new-product-page">
  <h1>New Product</h1>

 
  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path %>
  
</div>

app/views/products/show.html.erb
<div class ="container" id="product-details">
  <h1>Product Details</h1>
  <div class="row" data-product-id="<%= @product.id%>">
    <div class="col-md-6">
      <p><%= image_tag(@product.image_url, class: "img-responsive detail img-zoom", data_zoom_image: "@product.image_url_large") %></p>
    </div><!-- close column -->
      <div class="col-md-6">
        <p><strong>Name:</strong>
        <%= @product.name %></p>
        <p><strong>Colour:</strong>
        <%= @product.colour %></p>
        <p><strong>Price:</strong>
        <%= number_to_currency(@product.price) %></p>
      <div class="payment-btn">
        <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
        <p><div class="rated" data-score="<%= @product.average_rating %>"></div></p>
      </div>
        <p><strong>Description:</strong>
        <%= @product.description %></p>
      </div><!-- About product -->
    </div><!-- end row -->
</div><!-- end container -->

<div class= "container" id="review-rating-section">
  <div class="row">
    <div class="col-md-6">
      <% if signed_in? %>
      <h4>Add a review:</h4>
      <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
      <p><%= f.label :body, "Comments" %><br>
         <%= f.text_area :body, class: "form-control" %></p>
      <div class="rating">
        <h4>Rate me!</h4>
      </div> 
      <p><%= f.submit "Rate", class: "btn btn-default" %></p>
      <% end %>
      <% end %>
    </div><!-- end column -->
    
    <div class="col-md-6">
      <div  class="reviews-ratings product-reviews">
        <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
          <% @comments.each do |comment| %>
          <hr>
          <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
          <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <div class="rated" data-score="<%= comment.rating %>">
        </div>
          <p><%= comment.body %></p>
          <% end %>
      </div><!-- end reviews-->
    </div><!-- end column  -->
  </div><!-- end row -->
</div><!-- end container -->


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>