config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    resources :comments
  end
  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'static_pages#index'

  get 'static_pages/landing_page'
  
  get 'static_pages/about'
  
  get 'static_pages/contact'

  post 'static_pages/thank_you'

  post 'payments/create'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout' } , :controllers => { :registrations => "user_registrations" } 

  # actioncable
  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
      <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to "Cycle NYC", root_url %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Featured Products", static_pages_landing_page_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li><% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                <% else %>
                <%= link_to('Login', new_user_session_path) %>
                <% end %></li>
              <%= form_tag("/products",method: :get, class: "navbar-form navbar-right") do -%>
            <div class="form-group">
              <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
            </div>
              <%= submit_tag("Go", class: "btn btn-default") %>
            <% end -%>
         </ul>
        </div><!--/.nav-collapse -->
      </div><!-- end container -->
    </nav>
     
    <% if notice %>
      <div class="alert alert-info" role="alert">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p id="alert"><%= alert %></p>
      </div>
    <% end %>
  
	  <%= yield %>
  
    <footer class="footer">
      <div class="footer-main">
        <p>&copy; Cycle NYC 2016 .</p>
      </div>
    </footer>

  </body>
</html>